#if !canImport(ObjectiveC)
import XCTest

extension EventParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EventParserTests = [
        ("testAllowsNoLeadingSpace", testAllowsNoLeadingSpace),
        ("testCommentCanContainColon", testCommentCanContainColon),
        ("testDispatchesSingleLineMessage", testDispatchesSingleLineMessage),
        ("testDispatchesSingleLineMessageWithCustomEvent", testDispatchesSingleLineMessageWithCustomEvent),
        ("testDispatchesSingleLineMessageWIthId", testDispatchesSingleLineMessageWIthId),
        ("testDoesNotDispatchEmptyData", testDoesNotDispatchEmptyData),
        ("testDoesNotFireMultipleTimesIfSeveralEmptyLines", testDoesNotFireMultipleTimesIfSeveralEmptyLines),
        ("testDoesNotSetRetryTimeUnlessEntireValueIsNumeric", testDoesNotSetRetryTimeUnlessEntireValueIsNumeric),
        ("testEmptyDataWithBufferedDataAppendsNewline", testEmptyDataWithBufferedDataAppendsNewline),
        ("testEventNameResetAfterDispatch", testEventNameResetAfterDispatch),
        ("testInvalidFieldNameIgnoredInEvent", testInvalidFieldNameIgnoredInEvent),
        ("testLineWithoutColonTreatedAsFieldNameWithEmptyData", testLineWithoutColonTreatedAsFieldNameWithEmptyData),
        ("testMultipleDataDispatch", testMultipleDataDispatch),
        ("testOnlyLeadingSpaceTreatedAsEmpty", testOnlyLeadingSpaceTreatedAsEmpty),
        ("testRemovesOnlyFirstSpace", testRemovesOnlyFirstSpace),
        ("testReusesEventIdIfNotSet", testReusesEventIdIfNotSet),
        ("testSendsCommentsForLinesStartingWithColon", testSendsCommentsForLinesStartingWithColon),
        ("testSetsRetryTimeToSevenSeconds", testSetsRetryTimeToSevenSeconds),
    ]
}

extension LDSwiftEventSourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LDSwiftEventSourceTests = [
        ("testConfigDefaults", testConfigDefaults),
        ("testConfigModification", testConfigModification),
    ]
}

extension UTF8LineParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UTF8LineParserTests = [
        ("testBasicLine", testBasicLine),
        ("testBasicLineCr", testBasicLineCr),
        ("testBasicLineCrLf", testBasicLineCrLf),
        ("testBasicLineLf", testBasicLineLf),
        ("testBasicSplit", testBasicSplit),
        ("testCodePointSplitNotReplaced", testCodePointSplitNotReplaced),
        ("testEmptyCrLine", testEmptyCrLine),
        ("testEmptyData", testEmptyData),
        ("testInvalidCharacterReplaced", testInvalidCharacterReplaced),
        ("testInvalidCharacterReplacedOnNextLineAfterCr", testInvalidCharacterReplacedOnNextLineAfterCr),
        ("testMultiLineDataMixedLineEnding", testMultiLineDataMixedLineEnding),
        ("testNoData", testNoData),
        ("testPartialReplacedOnClose", testPartialReplacedOnClose),
        ("testUnicodeString", testUnicodeString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EventParserTests.__allTests__EventParserTests),
        testCase(LDSwiftEventSourceTests.__allTests__LDSwiftEventSourceTests),
        testCase(UTF8LineParserTests.__allTests__UTF8LineParserTests),
    ]
}
#endif
