name: Lint
description: 'Run swiftlint.'

runs:
  using: composite
  steps:
    - name: Install swiftlint
      shell: bash
      run: brew install swiftlint

    - name: Run swiftlint
      shell: bash
      run: swiftlint lint
