name: Lint PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr-title:
    uses: launchdarkly/gh-actions/.github/workflows/lint-pr-title.yml@main
