name: Publish Package
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Is this a dry run. If so no package will be published.'
        type: boolean
        required: true

jobs:
  build-publish:
    runs-on: macos-15

    # Needed to get tokens during publishing.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        name: 'Get Cocoapods token'
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/production/common/releasing/cocoapods/token = COCOAPODS_TRUNK_TOKEN'

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: 16.4

      - uses: ./.github/actions/lint

      - uses: ./.github/actions/build-ios
        with:
          ios-sim: 'platform=iOS Simulator,name=iPhone 16'

      - uses: ./.github/actions/build-macos

      - uses: ./.github/actions/build-tvos

      - uses: ./.github/actions/build-watchos

      - uses: ./.github/actions/test-swiftpm

      - uses: ./.github/actions/contract-tests
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/publish
        with:
          dry_run: ${{ inputs.dry_run }}
